EXSWHTEC-262 - Implement tests for atomic add operations.
ROCm-Developer-Tools/hip-tests pull request #393
Opened 2023-08-10 11:35 UTC by mirza-halilcevic

Depends-on: #392

2023-08-18 14:41 UTC, scchan requested changes

2023-08-18 14:41 UTC, scchan commented on catch/unit/atomics/atomicAdd.cc
> +  int expected_error_count{8};
We need clear documentation as to which are the eight expected errors.

2023-08-25 13:54 UTC, scchan commented on catch/unit/atomics/atomicAdd.cc
> +  int expected_error_count{8};
Also can we test those 8 errors separately?

2024-03-07 06:44 UTC, rakesroy commented
PR has been merged into develop branch via commit e70cadd514f34df13f9d6786c54b11917be7b02e.

2024-03-07 06:44 UTC, closed without merging